[package]
name = "sciport-rs"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
complex-bessel-rs = { path = "../complex-bessel-rs", version = "0.0.4" }
ndarray = { version = "0.15.6", features = ["rayon"] }

