[package]
name = "sci-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nrfind = "1.0.3"
num = "0.4.0"
complex-bessel-rs = { path = "../complex-bessel-rs", version = "0.0.1" }

