[package]
name = "sciport-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
complex-bessel-rs = { path = "../complex-bessel-rs", version = "0.0.3" }

